### ISSUE TITLE
index out of range at parser.go in readPtr

### ISSUE THREAD

**Issue by aababilov** [randall77/heapdump14#2]
```
Loading...
panic: runtime error: index out of range

goroutine 1 [running]:
encoding/binary.littleEndian.Uint64(0x4c208457468, 0x0, 0x0, 0x4c20814fbc0)
        /usr/lib/google-golang/src/encoding/binary/binary.go:71 +0x11c
encoding/binary.(*littleEndian).Uint64(0x9a5ed8, 0x4c208457468, 0x0, 0x0, 0x4c20814fbc0)
        <autogenerated>:12 +0xb5
github.com/randall77/heapdump14/read.readPtr(0x4c20805e000, 0x4c208457468, 0x0, 0x0, 0x4eb650)
        /home/aababilov/go/src/github.com/randall77/heapdump14/read/parser.go:2116 +0xc0
github.com/randall77/heapdump14/read.(*Dump).appendEdge(0x4c20805e000, 0x0, 0x0, 0x0, 0x4c208457468, 0x8, 0x8, 0x8, 0x2, 0x0, ...)
        /home/aababilov/go/src/github.com/randall77/heapdump14/read/parser.go:1384 +0xb9
github.com/randall77/heapdump14/read.(*Dump).appendFields(0x4c20805e000, 0x0, 0x0, 0x0, 0x4c208457468, 0x8, 0x8, 0x4c20847c210, 0x1, 0x1, ...)
        /home/aababilov/go/src/github.com/randall77/heapdump14/read/parser.go:1439 +0x5fc
github.com/randall77/heapdump14/read.link2(0x4c20805e000)
        /home/aababilov/go/src/github.com/randall77/heapdump14/read/parser.go:1930 +0xf5
github.com/randall77/heapdump14/read.Read(0x7fffd5d46b86, 0x34, 0x0, 0x0, 0x0)
        /home/aababilov/go/src/github.com/randall77/heapdump14/read/parser.go:2103 +0xab
main.main()
        /home/aababilov/go/src/github.com/randall77/heapdump14/hview/main.go:893 +0x1f2
```

**Comment by randall77** [comment]
Should be fixed now.
